- name: Import the key for the official MongoDB repository.
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: Setup Debian MongoDB {{ mongodb_install_major }}.{{ mongodb_install_minor }} repository
  copy:
    dest: /etc/apt/sources.list.d/mongodb-org-{{ mongodb_install_major }}.{{ mongodb_install_minor }}.list
    content: "deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_install_major }}.{{ mongodb_install_minor }} main"
  when: ansible_distribution != 'Ubuntu'

- name: Setup Ubuntu MongoDB {{ mongodb_install_major }}.{{ mongodb_install_minor }} repository
  copy:
    dest: /etc/apt/sources.list.d/mongodb-org-{{ mongodb_install_major }}.{{ mongodb_install_minor }}.list
    content: "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_install_major }}.{{ mongodb_install_minor }} multiverse"
  when: ansible_distribution == 'Ubuntu'

- name: install MongoDB package
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - mongodb-org
    - numactl
    - python-pip
