---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint
platforms:
  - name: centos7_5
    image: centos:7.5.1804
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos7_4
    image: centos:7.4.1708
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos7_3
    image: centos:7.3.1611
    command: /usr/sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: xenial
    image: ubuntu:xenial
    command: /sbin/init
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint: |
    ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint: |
    flake8
