---
- name: Converge
  hosts: all
  roles:
    - role: stone-payments.epel
      when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
    - role: stone-payments.mongodb
