---
- name: stone-payments.nohugepages
  src: https://github.com/stone-payments/ansible-nohugepages.git
  scm: git

- name: stone-payments.epel
  src: https://github.com/stone-payments/ansible-epel.git
  scm: git
